### ISSUE TITLE
Upgrade to pdfbox 2.0?

### ISSUE THREAD

**Issue by kapil-mangtani** [thoqbk/traprange#3]
Hi,

Nice work! Are you planning to migrate to pdfbox 2.0??
The new API has vastly improved and it would be a big plus for the users wishing to migrate to pdfbox 2.0, since many functions have moved/been deleted along with some classes.

Would love to hear back!
Cheers

**Comment by arunnane** [comment]
Yes, would be very useful if pdfbox 2.0 migration is added.

Thanks.

**Comment by thoqbk** [comment]
Hi,
I have just updated `traprange` to support PDFBox 2.0
Sorry because of my late!
Thank you!

**Comment by arunnane** [comment]
Thanks a lot.
