### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by slycaon** [thoqbk/traprange#4]
Hi. This is a really great package. Thanks so much.

I'm having one issue with exporting to CSV:

String csv = tables.get(0).toString();

I have a PDF table where the first column is sometimes empty. TrapRange discovers the column just fine, and export to HTML shows the column with the empty cell. But when I export to CSV, the empty cells are lost with no starting semicolon to denote them.

Do you experience the same?

Mike

**Comment by thoqbk** [comment]
Hi Mike! It's a bug and I have just fixed it.

Thank you so much!
